theme: jekyll-theme-cayman

title: [NadicaSm]
description: [This is a personal A short description of your site's purpose]

show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
